### ISSUE TITLE
LURe does not recognize itself(`lure-bin`) as installed

### ISSUE THREAD

**Issue by atirut-w** [lure-sh/lure#77]
This causes LURe to not be updated when running `lure refresh && lure upgrade`. Can be fixed by running `lure install lure-bin`

**Comment by Elara6331** [comment]
This should be fixed now that the lure packages in the repo have been renamed

**Comment by atirut-w** [comment]
![image](https://github.com/lure-sh/lure/assets/25323231/c1ef9e66-ac82-4819-ac8c-14330f9cdd82)


Still a problem with the latest version. I tried clearing the cache directory, removing lure and reinstalling it but it still does not recognize itself as installed. I think the prebuilt itself needs a `-bin`/`-git` suffix?
