### ISSUE TITLE
Unable to install on openSUSE Leap 15.5: 'Package header is not signed'

### ISSUE THREAD

**Issue by Gersonzao** [lure-sh/lure#83]
```
[INFO] Detected zypper
[INFO] Found latest LURE version: v0.1.3
[INFO] Downloading LURE package
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.8M  100 18.8M    0     0  1137k      0  0:00:16  0:00:16 --:--:-- 1352k
[INFO] Installing LURE package
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following recommended package was automatically selected:
  aria2

The following 4 NEW packages are going to be installed:
  aria2 aria2-lang libaria2-0 linux-user-repository

4 new packages to install.
Overall download size: 18.8 MiB. Already cached: 1.5 MiB. After the operation, additional 40.4 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
In cache libaria2-0-1.36.0-bp155.2.20.x86_64.rpm                                                                          (1/4),   1.1 MiB    
In cache aria2-1.36.0-bp155.2.20.x86_64.rpm                                                                               (2/4), 186.4 KiB    
In cache aria2-lang-1.36.0-bp155.2.20.noarch.rpm                                                                          (3/4), 215.7 KiB    
Retrieving: linux-user-repository-0.1.3-1.x86_64 (Plain RPM files cache)                                                  (4/4),  18.8 MiB    
lure.CIwcjeB0gK.rpm:
    Package header is not signed!

linux-user-repository-0.1.3-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): a
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.                                                                                                    
Please see the above error message for a hint.
[INFO] Cleaning up
[INFO] Done!
```

**Comment by Elara6331** [comment]
I've just updated the script to accept the package even if it's unsigned. Can you try again and see if that fixed it?

**Comment by Chirunos** [comment]
> I've just updated the script to accept the package even if it's unsigned. Can you try again and see if that fixed it?

It works now, thanks!
I'm still getting this, but I guess it's normal:
```
lure.7aehSoMwSB.rpm:
    Package header is not signed!
linux-user-repository-0.1.3-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Accepting package despite the error. (--no-gpg-checks)
```
